arg_name: field
description: |-
  The name of the failure point.
interface: dbcommand
name: configureFailPoint
operation: configureFailPoint
optional: false
position: 1
type: string
---
arg_name: field
description: |
  Controls the behavior of a failure point. The possible values are
  ``alwaysOn``, ``off``, or a document in the form of ``{times: n}``
  that specifies the number of times the failure point remains on
  before it deactivates. The maximum value for the number is a
  32-bit signed integer.
interface: dbcommand
name: mode
operation: configureFailPoint
optional: false
position: 2
type:
- document
- string
---
arg_name: field
description: |
  Passes in additional data for use in configuring the fail point. For
  example, to imitate a slow connection pass in a document that
  contains a delay time.
interface: dbcommand
name: data
operation: configureFailPoint
optional: true
position: 3
type: document
...
