arg_name: param
description: |
  A :doc:`document </reference/replica-configuration>` that specifies
  the configuration of a replica set.
interface: method
name: configuration
operation: rs.reconfig
optional: false
position: 1
type: document
---
arg_name: param
description: |
  If set as ``{ force: true }``, this forces the replica set to
  accept the new configuration even if a majority of the members are
  not accessible. Use with caution, as this can lead to
  :term:`rollback` situations.
interface: method
name: force
operation: rs.reconfig
optional: true
position: 2
type: document
...
